# Generated by Codex on 2026-02-04

from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_product_to_service(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Service = apps.get_model("core", "Service")
    InvoiceItem = apps.get_model("invoices", "InvoiceItem")

    product_to_service = {}

    for product in Product.objects.all():
        service, _ = Service.objects.get_or_create(
            name=product.name,
            defaults={"price": product.price},
        )
        product_to_service[product.id] = service.id

    for item in InvoiceItem.objects.exclude(product_id=None):
        service_id = product_to_service.get(item.product_id)
        if service_id:
            item.service_id = service_id
            item.save(update_fields=["service"])

    # Ensure baseline services exist
    for base_name in ["CNC", "PVC", "Cutting", "Carpentry"]:
        Service.objects.get_or_create(name=base_name, defaults={"price": 0})


def backwards_copy_service_to_product(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Service = apps.get_model("core", "Service")
    InvoiceItem = apps.get_model("invoices", "InvoiceItem")

    service_to_product = {}

    for service in Service.objects.all():
        product, _ = Product.objects.get_or_create(
            name=service.name,
            defaults={"price": service.price, "quantity": 0},
        )
        service_to_product[service.id] = product.id

    for item in InvoiceItem.objects.exclude(service_id=None):
        product_id = service_to_product.get(item.service_id)
        if product_id:
            item.product_id = product_id
            item.save(update_fields=["product"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_companysetting_service"),
        ("products", "0001_initial"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="service",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.service",
            ),
        ),
        migrations.RunPython(
            forwards_copy_product_to_service,
            backwards_copy_service_to_product,
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="product",
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.service",
            ),
        ),
    ]
